#!/usr/bin/env bash
# Interactive helper: writes .env next to this script for docker compose.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${ROOT}/.env"

echo "PoloDeck Docker setup"
echo "---------------------"
echo "Default: API and UIs bind to 127.0.0.1 (localhost only)."
echo "For Raspberry Pis or other machines on the same Wi‑Fi, choose LAN binding (0.0.0.0)."
echo ""

read -r -p "Bind services on all interfaces (0.0.0.0) for LAN access? [y/N] " LAN
if [[ "${LAN,,}" == "y" || "${LAN,,}" == "yes" ]]; then
  BIND="0.0.0.0"
else
  BIND="127.0.0.1"
fi

read -r -p "Include arena scoreboard / timer / shot-clock static container (compose profile arena)? [y/N] " ARENA
if [[ "${ARENA,,}" == "y" || "${ARENA,,}" == "yes" ]]; then
  PROFILE="arena"
else
  PROFILE=""
fi

{
  echo "# Generated by setup.sh — edit as needed"
  echo "POLODECK_BIND_ADDRESS=${BIND}"
  if [[ -n "${PROFILE}" ]]; then
    echo "COMPOSE_PROFILES=${PROFILE}"
  fi
} > "${ENV_FILE}"

echo ""
echo "Wrote ${ENV_FILE}"
echo "Start the stack:"
echo "  cd \"${ROOT}\" && docker compose up -d --build"
echo ""
echo "Arena UI (if enabled): http://localhost:8090/?server=http://<this-host-ip>:3000&gameId=<GAME_ID>"
